import OpenAI from "openai";
import { z } from "zod";

// Zod schema for single question generated by LLM
export const generatedQuestionSchema = z.object({
  question: z.string().min(5, "Question must be at least 5 characters"),
  options: z
    .array(z.string().min(1, "Option cannot be empty"))
    .length(4, "Exactly 4 options required"),
  correctIndex: z
    .number()
    .int()
    .min(0)
    .max(3, "correctIndex must be between 0 and 3"),
  explanation: z
    .string()
    .min(5, "Explanation must be at least 5 characters"),
});

export const generatedBatchSchema = z.object({
  questions: z.array(generatedQuestionSchema),
});

export type GeneratedQuestion = z.infer<typeof generatedQuestionSchema>;

export interface GenerateOptions {
  textChunk: string;
  questionCount: number;
  subjectName: string;
  topicName?: string;
  difficulty: "EASY" | "MEDIUM" | "HARD" | "MIXED";
}

export interface AiGenerationResult {
  questions: GeneratedQuestion[];
  tokensUsed: number;
  modelUsed: string;
}

/**
 * Helper to initialize the OpenAI client with environment variables
 */
export function getOpenAIClient(): { client: OpenAI; model: string } {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey || apiKey.trim() === "") {
    throw new Error(
      "OPENAI_API_KEY is not configured in your environment variables (.env). Please add OPENAI_API_KEY to generate questions using AI."
    );
  }

  const baseURL = process.env.OPENAI_BASE_URL || "https://api.openai.com/v1";
  const model = process.env.OPENAI_MODEL || "gpt-4o-mini";

  const client = new OpenAI({
    apiKey,
    baseURL,
    timeout: 45000, // 45 seconds timeout
  });

  return { client, model };
}

/**
 * System prompt strictly adhering to Section 6 of CBT Trainer specifications
 */
function buildSystemPrompt(
  count: number,
  subject: string,
  topic: string | undefined,
  difficulty: string
): string {
  return `You are an expert exam question creator for the Punjab Government Group B Computer Programmer recruitment CBT exam.
Your task is to generate exactly ${count} high-quality, technically accurate single-answer Multiple Choice Questions (MCQs) for the subject "${subject}"${
    topic ? ` and topic "${topic}"` : ""
  }.

RULES THAT YOU MUST STRICTLY FOLLOW:
1. Grounding: Every single question must be grounded ONLY in the provided text. Do NOT ask questions whose answers cannot be verified from the text.
2. Structure: Each question must have:
   - Concise, clear question text.
   - EXACTLY 4 options (Option 0, Option 1, Option 2, Option 3).
   - EXACTLY ONE clearly correct answer.
   - Exactly 3 plausible, technically reasonable distractors (not obviously silly or absurd).
   - A short explanation (1-3 sentences) referencing what the source text says.
3. Code blocks: If the source text contains code, snippets, or SQL queries, you may include verbatim code snippets formatted in fenced markdown code blocks (e.g. \`\`\`c ... \`\`\`, \`\`\`sql ... \`\`\`).
4. Difficulty: Target difficulty level is "${difficulty}".
5. Language: English only. Keep technical terms in standard English.
6. Format: You MUST output STRICT JSON only in the following schema with no extra conversational commentary:
{
  "questions": [
    {
      "question": "Question text here",
      "options": ["Option A text", "Option B text", "Option C text", "Option D text"],
      "correctIndex": 0,
      "explanation": "Brief explanation referencing the source text."
    }
  ]
}`;
}

/**
 * Clean and parse JSON response from LLM (handles markdown code blocks or trailing commas)
 */
function extractAndParseJson(raw: string): unknown {
  let cleaned = raw.trim();

  // Strip ```json and ``` code fence if present
  if (cleaned.startsWith("```")) {
    cleaned = cleaned.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
  }

  // Find first { and last }
  const firstBrace = cleaned.indexOf("{");
  const lastBrace = cleaned.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
    cleaned = cleaned.slice(firstBrace, lastBrace + 1);
  }

  return JSON.parse(cleaned);
}

/**
 * Generate questions using the OpenAI adapter with retry on JSON parse failure
 */
export async function generateQuestionsWithAi(
  options: GenerateOptions
): Promise<AiGenerationResult> {
  const { client, model } = getOpenAIClient();

  const systemPrompt = buildSystemPrompt(
    options.questionCount,
    options.subjectName,
    options.topicName,
    options.difficulty
  );

  const userPrompt = `SOURCE TEXT:
---
${options.textChunk}
---

Generate exactly ${options.questionCount} MCQs adhering strictly to the JSON schema.`;

  let lastError: Error | null = null;

  // Try up to 2 times
  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      const response = await client.chat.completions.create({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3,
        response_format: { type: "json_object" },
      });

      const content = response.choices[0]?.message?.content;
      if (!content) {
        throw new Error("Received empty response from AI model.");
      }

      const parsedData = extractAndParseJson(content);
      const validated = generatedBatchSchema.parse(parsedData);

      const tokensUsed = response.usage?.total_tokens ?? 0;

      return {
        questions: validated.questions.slice(0, options.questionCount),
        tokensUsed,
        modelUsed: model,
      };
    } catch (err: unknown) {
      lastError = err instanceof Error ? err : new Error(String(err));
      // If first attempt failed and it's a parsing error, retry once
      if (attempt === 1) {
        continue;
      }
    }
  }

  throw lastError || new Error("Failed to generate questions from AI.");
}
